create table if not exists public.retailcrm_orders (
    retailcrm_id bigint primary key,
    external_id text,
    number text,
    site text,
    status text,
    order_type text,
    order_method text,
    first_name text,
    last_name text,
    phone text,
    email text,
    city text,
    delivery_address text,
    total_summ numeric,
    items_count integer,
    total_quantity numeric,
    created_at timestamptz,
    updated_at timestamptz,
    status_updated_at timestamptz,
    customer_comment text,
    manager_comment text,
    raw jsonb not null
);
